-- MySQL Script generated by MySQL Workbench
-- Thu Apr 29 09:46:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema historisation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema historisation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `historisation` DEFAULT CHARACTER SET utf8mb4 ;
USE `historisation` ;

-- -----------------------------------------------------
-- Table `historisation`.`adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historisation`.`adresses` (
  `idadresses` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `typevoie` VARCHAR(45) NOT NULL,
  `nomvoie` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `cp` INT NOT NULL,
  PRIMARY KEY (`idadresses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historisation`.`societes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historisation`.`societes` (
  `idsocietes` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `siren` INT NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `dateImmatriculation` DATETIME NOT NULL,
  `capital` INT NOT NULL,
  `adresses_idadresses` INT NOT NULL,
  PRIMARY KEY (`idsocietes`),
  INDEX `fk_societes_adresses_idx` (`adresses_idadresses` ASC),
  CONSTRAINT `fk_societes_adresses`
    FOREIGN KEY (`adresses_idadresses`)
    REFERENCES `historisation`.`adresses` (`idadresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historisation`.`listejuridique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historisation`.`listejuridique` (
  `idlistejuridique` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  `societes_idsocietes` INT NOT NULL,
  PRIMARY KEY (`idlistejuridique`),
  INDEX `fk_listejuridique_societes1_idx` (`societes_idsocietes` ASC),
  CONSTRAINT `fk_listejuridique_societes1`
    FOREIGN KEY (`societes_idsocietes`)
    REFERENCES `historisation`.`societes` (`idsocietes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
